### PR TITLE
Add support for multiple delimeted values files

### PR DESCRIPTION
**Pull request by domi2120**
Multiple values files can be specified by separating them with ";"

### CODE REVIEW

**Review by ckittelmann — COMMENTED** [review]
works as expected, but I think its hard to understand.
@domi2120 should we consider using a loop instead of the map syntax? I think its easier to understand, example
```
IN="abc;123;"
for i in $(echo $IN | tr ";" "\n")
do
  if [ ! -z "$i" ]
  then
    echo $i "1"
  fi
done
```

**Comment by agentschmitt** [comment]
@ckittelmann @domi2120 multple value files are already supported as comma seperated list.
see example: values_file: Helm/environments/staging.yaml,Helm/environments/staging-${{ matrix.brand }}.yaml
full sourde: https://github.com/SamhammerAG/selfserviceportal/blob/dev/.github/workflows/cicd.yml#L423

**Comment by agentschmitt** [comment]
can we close this pr and just update documentation. or do i oversee somethings why we need this other solution?

**Comment by ckittelmann** [comment]
yeah then just update documentation and close PR

**Pull request closed without merging**
